name: ESLint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: volta-cli/action@v1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - uses: reviewdog/action-eslint@v1
        with:
          eslint_flags: "."
